export default [
    {
        "id": "card_6_hearts",
        "suit": "hearts",
        "rank": "6",
        "trump": false, // false,
        "status": "user2",
    },
    {
        "id": "card_7_hearts",
        "suit": "hearts",
        "rank": "7",
        "trump": false, // false, 
        "status": "user2",
    },
    {
        "id": "card_8_hearts",
        "suit": "hearts",
        "rank": "8",
        "trump": false, // false, 
        "status": "user2",
    },
    {
        "id": "card_9_hearts",
        "suit": "hearts",
        "rank": "9",
        "trump": false, // false, 
        "status": "user2",
    },
    {
        "id": "card_10_hearts",
        "suit": "hearts",
        "rank": "10",
        "trump": false, // false, 
        "status": "user2",
    },
    {
        "id": "card_J_hearts",
        "suit": "hearts",
        "rank": "J",
        "trump": false, // false, 
        "status": "user2",
    },
    {
        "id": "card_Q_hearts",
        "suit": "hearts",
        "rank": "Q",
        "trump": false, // false, 
        "status": "user5",
    },
    {
        "id": "card_K_hearts",
        "suit": "hearts",
        "rank": "K",
        "trump": false, // false, 
        "status": "user5",
    },
    {
        "id": "card_A_hearts",
        "suit": "hearts",
        "rank": "A",
        "trump": false, // false, 
        "status": "user5",
    },
    {
        "id": "card_6_clubs",
        "suit": "clubs",
        "rank": "6",
        "trump": false, // false, 
        "status": "user6",
    },
    {
        "id": "card_7_clubs",
        "suit": "clubs",
        "rank": "7",
        "trump": false, // false, 
        "status": "user6",
    },
    {
        "id": "card_8_clubs",
        "suit": "clubs",
        "rank": "8",
        "trump": false, // false, 
        "status": "user6",
    },
    {
        "id": "card_9_clubs",
        "suit": "clubs",
        "rank": "9",
        "trump": false, // false, 
        "status": "user6",
    },
    {
        "id": "card_10_clubs",
        "suit": "clubs",
        "rank": "10",
        "trump": false, // false, 
        "status": "user6",
    },
    {
        "id": "card_J_clubs",
        "suit": "clubs",
        "rank": "J",
        "trump": false, // false, 
        "status": "user6",
    },
    {
        "id": "card_Q_clubs",
        "suit": "clubs",
        "rank": "Q",
        "trump": false, // false, 
        "status": "user3",
    },
    {
        "id": "card_K_clubs",
        "suit": "clubs",
        "rank": "K",
        "trump": false, // false, 
        "status": "user3",
    },
    {
        "id": "card_A_clubs",
        "suit": "clubs",
        "rank": "A",
        "trump": false, // false, 
        "status": "user3",
    },
    {
        "id": "card_6_diamonds",
        "suit": "diamonds",
        "rank": "6",
        "trump": false, // false, 
        "status": "user3",
    },
    {
        "id": "card_7_diamonds",
        "suit": "diamonds",
        "rank": "7",
        "trump": false, // false, 
        "status": "user3",
    },
    {
        "id": "card_8_diamonds",
        "suit": "diamonds",
        "rank": "8",
        "trump": false, // false, 
        "status": "user3",
    },
    {
        "id": "card_9_diamonds",
        "suit": "diamonds",
        "rank": "9",
        "trump": false, // false, 
        "status": "user4",
    },
    {
        "id": "card_10_diamonds",
        "suit": "diamonds",
        "rank": "10",
        "trump": false, // false, 
        "status": "user4",
    },
    {
        "id": "card_J_diamonds",
        "suit": "diamonds",
        "rank": "J",
        "trump": false, // false, 
        "status": "user4",
    },
    {
        "id": "card_Q_diamonds",
        "suit": "diamonds",
        "rank": "Q",
        "trump": false, // false, 
        "status": "user4",
    },
    {
        "id": "card_K_diamonds",
        "suit": "diamonds",
        "rank": "K",
        "trump": false, // false, 
        "status": "user4",
    },
    {
        "id": "card_A_diamonds",
        "suit": "diamonds",
        "rank": "A",
        "trump": false, // false, 
        "status": "user4",
    },
    {
        "id": "card_6_spades",
        "suit": "spades",
        "rank": "6",
        "trump": false, // false, 
        "status": "user1",
    },
    {
        "id": "card_7_spades",
        "suit": "spades",
        "rank": "7",
        "trump": false, // false, 
        "status": "user1",
    },
    {
        "id": "card_8_spades",
        "suit": "spades",
        "rank": "8",
        "trump": false, // false, 
        "status": "user1",
    },
    {
        "id": "card_9_spades",
        "suit": "spades",
        "rank": "9",
        "trump": false, // false, 
        "status": "user1",
    },
    {
        "id": "card_10_spades",
        "suit": "spades",
        "rank": "10",
        "trump": false, // false, 
        "status": "user1",
    },
    {
        "id": "card_J_spades",
        "suit": "spades",
        "rank": "J",
        "trump": false, // false, 
        "status": "user1",
    },
    {
        "id": "card_Q_spades",
        "suit": "spades",
        "rank": "Q",
        "trump": false, // false, 
        "status": "user5",
    },
    {
        "id": "card_K_spades",
        "suit": "spades",
        "rank": "K",
        "trump": false, // false, 
        "status": "user5",
    },
    {
        "id": "card_A_spades",
        "suit": "spades",
        "rank": "A",
        "trump": false, // false, 
        "status": "user5",
    },
]